spring:
  profiles:
    active: development
  application:
    name: spring_exos
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
server:
  port: 8081
